In [5]:
import pandas as pd
import numpy as np
# use .dot format to visualize a tree
from ipywidgets import Image
from io import StringIO
import pydotplus #pip install pydotplus
from sklearn.tree import export_graphviz

In [45]:
EOS_FAM = pd.read_csv('EOS.csv', delimiter=';')
EOS_FAM

,NUMBER,NAME,DESIG,FAM,S,CLASS,S.1,F,DIA,S.2,...,F.3,AMIN,AMAX,U,NOTES,BIN,PRI,SAM,SD,WF
0,221.0,Eos,NaN,EOS,S,K,S,NaN,103.87,M,...,NaN,0.05,0.12,3.0,NaN,NaN,NaN,Y,NaN,NaN
1,320.0,Katharina,NaN,EOS,A,S,C,NaN,24.57,M,...,NaN,0.19,0.21,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,339.0,Dorothea,1892 G,EOS,S,K,S,NaN,38.25,M,...,NaN,0.06,0.10,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,450.0,Brigitta,1899 EV,EOS,T,CSU,D,NaN,33.46,M,...,NaN,0.22,0.31,3.0,NaN,NaN,NaN,Y,NaN,NaN
4,513.0,Centesima,1903 LY,EOS,S,K,S,NaN,50.15,M,...,NaN,0.18,0.45,3.0,NaN,NaN,NaN,Y,NaN,NaN
5,520.0,Franziska,1903 MV,EOS,T,CGU,D,NaN,28.61,L,...,NaN,0.35,0.51,3.0,NaN,NaN,NaN,Y,NaN,NaN
6,529.0,Preziosa,1904 NT,EOS,T,S,D,NaN,31.84,L,...,NaN,NaN,0.56,2.0,NaN,NaN,NaN,Y,NaN,NaN
7,562.0,Salome,1905 QH,EOS,T,S,D,NaN,30.56,L,...,NaN,0.17,0.37,3.0,-,NaN,NaN,Y,NaN,NaN
8,573.0,Recha,1905 RC,EOS,A,S,D,NaN,48.21,M,...,NaN,0.20,0.34,3.0,NaN,NaN,NaN,Y,NaN,NaN
9,579.0,Sidonia,1905 SD,EOS,S,K,D,NaN,85.95,L,...,NaN,0.02,0.28,3.0,-,NaN,NaN,Y,NaN,NaN
10,590.0,Tomyris,1906 TO,EOS,A,S,D,NaN,39.78,L,...,NaN,0.21,0.93,3.0,NaN,NaN,NaN,Y,NaN,NaN
11,608.0,Adolfine,1906 VD,EOS,A,S,D,NaN,25.39,M,...,NaN,0.16,0.37,3.0,NaN,NaN,NaN,Y,NaN,NaN
12,633.0,Zelima,1907 ZM,EOS,S,S,S,NaN,34.37,M,...,NaN,0.14,0.49,3.0,NaN,NaN,NaN,NaN,NaN,NaN
13,639.0,Latona,1907 ZT,EOS,T,S,D,NaN,70.80,L,...,NaN,0.07,0.35,3.0,NaN,NaN,NaN,Y,NaN,NaN
14,651.0,Antikleia,1907 AN,EOS,T,S,S,NaN,33.04,M,...,NaN,0.13,0.41,3.0,NaN,NaN,NaN,Y,NaN,NaN
15,653.0,Berenike,1907 BK,EOS,S,K,D,NaN,39.18,L,...,NaN,0.03,0.11,3.0,NaN,NaN,NaN,NaN,NaN,NaN
16,661.0,Cloelia,1908 CL,EOS,S,K,D,NaN,48.08,M,...,NaN,NaN,0.26,3.0,NaN,NaN,NaN,NaN,NaN,NaN
17,669.0,Kypria,1908 DQ,EOS,T,S,S,NaN,31.75,M,...,NaN,0.17,0.64,3.0,NaN,NaN,NaN,Y,NaN,NaN
18,742.0,Edisona,1913 QU,EOS,S,K,S,NaN,45.60,M,...,NaN,0.24,0.30,3.0,NaN,NaN,NaN,Y,NaN,NaN
19,766.0,Moguntia,1913 SW,EOS,T,MU,D,NaN,31.18,L,...,NaN,0.06,0.23,3.0,NaN,NaN,NaN,NaN,NaN,NaN
20,775.0,Lumiere,1914 TX,EOS,T,S,D,NaN,33.54,L,...,NaN,0.19,0.28,3.0,NaN,NaN,NaN,Y,NaN,NaN
21,798.0,Ruth,1914 VT,EOS,T,M,D,NaN,43.01,M,...,NaN,0.19,0.36,3.0,NaN,NaN,NaN,Y,NaN,NaN
22,807.0,Ceraskia,1915 WY,EOS,T,S,D,NaN,26.15,L,...,NaN,0.25,0.49,3.0,NaN,NaN,NaN,Y,NaN,NaN
23,833.0,Monica,1916 AC,EOS,A,S,C,NaN,21.40,M,...,NaN,0.11,0.19,3.0,NaN,NaN,NaN,NaN,NaN,NaN
24,890.0,Waltraut,1918 DK,EOS,T,CTGU:,S,NaN,27.33,M,...,NaN,0.30,0.36,3.0,NaN,NaN,NaN,Y,NaN,NaN
25,992.0,Swasey,1922 ND,EOS,A,S,D,NaN,27.52,M,...,NaN,NaN,0.17,2.0,NaN,NaN,NaN,NaN,NaN,NaN
26,1033.0,Simona,1924 SM,EOS,A,S,D,NaN,24.71,M,...,NaN,NaN,0.04,1.0,+,NaN,NaN,NaN,NaN,NaN
27,1075.0,Helina,1926 SC,EOS,T,SU,S,NaN,35.52,S,...,NaN,0.64,0.91,3.0,-,NaN,NaN,Y,NaN,NaN
28,1087.0,Arabis,1927 RD,EOS,T,S,D,NaN,31.67,L,...,NaN,0.14,0.40,3.0,NaN,NaN,NaN,Y,NaN,NaN
29,1095.0,Tulipa,1926 GS,EOS,A,S,D,NaN,31.53,L,...,NaN,0.14,0.23,3.0,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,167631.0,2004 CE87,2004 CE87,EOS,A,S,C,NaN,3.39,M,...,NaN,0.33,0.41,2.0,NaN,NaN,NaN,NaN,NaN,Y
445,177075.0,2003 FR36,2003 FR36,EOS,A,S,D,NaN,2.29,T,...,NaN,NaN,0.37,2.0,+,NaN,NaN,NaN,NaN,NaN
446,178014.0,2006 RG,2006 RG,EOS,A,S,C,NaN,2.90,T,...,NaN,NaN,0.48,2.0,NaN,NaN,NaN,NaN,NaN,Y
447,184616.0,2005 RE11,2005 RE11,EOS,A,S,C,NaN,2.88,T,...,NaN,NaN,0.86,2.0,NaN,NaN,NaN,NaN,NaN,Y
448,195704.0,2002 PH35,2002 PH35,EOS,A,S,C,NaN,2.50,T,...,NaN,NaN,0.36,2.0,NaN,NaN,NaN,NaN,NaN,Y
449,196806.0,2003 SQ218,2003 SQ218,EOS,A,S,C,NaN,2.66,T,...,NaN,NaN,0.30,2.0,NaN,NaN,NaN,NaN,NaN,Y
450,201297.0,2002 SK60,2002 SK60,EOS,A,S,C,NaN,2.21,T,...,NaN,NaN,0.83,2.0,-,NaN,NaN,NaN,NaN,Y
451,201369.0,2002 TA278,2002 TA278,EOS,A,S,C,NaN,3.72,M,...,NaN,0.74,0.77,2.0,NaN,NaN,NaN,NaN,NaN,Y
452,202321.0,2005 EG55,2005 EG55,EOS,A,S,C,NaN,2.01,T,...,NaN,NaN,0.59,2.0,NaN,NaN,NaN,NaN,NaN,Y
453,213779.0,2003 EP14,2003 EP14,EOS,A,C,C,NaN,2.95,M,...,NaN,NaN,0.96,2.0,NaN,NaN,NaN,NaN,NaN,Y
454,224958.0,2007 EM18,2007 EM18,EOS,A,S,C,NaN,2.24,M,...,NaN,NaN,NaN,NaN,HN,NaN,NaN,NaN,NaN,Y
455,226971.0,2004 VH112,2004 VH112,EOS,A,S,C,NaN,2.30,T,...,NaN,NaN,0.76,2.0,NaN,NaN,NaN,NaN,NaN,Y
456,237286.0,2008 XB21,2008 XB21,EOS,A,S,C,NaN,3.09,M,...,NaN,NaN,NaN,NaN,HN,NaN,NaN,NaN,NaN,Y
457,249738.0,2000 SB159,2000 SB159,EOS,A,S,D,NaN,2.21,T,...,NaN,NaN,0.11,1.0,+,NaN,NaN,NaN,NaN,NaN
458,255093.0,2005 UW48,2005 UW48,EOS,A,S,C,NaN,2.15,T,...,NaN,NaN,0.41,2.0,NaN,NaN,NaN,NaN,NaN,Y
459,274707.0,2008 UG100,2008 UG100,EOS,A,S,C,NaN,2.09,T,...,NaN,NaN,0.76,2.0,NaN,NaN,NaN,NaN,NaN,Y
460,286096.0,2001 TR47,2001 TR47,EOS,A,S,C,NaN,2.08,T,...,NaN,NaN,0.62,2.0,NaN,NaN,NaN,NaN,NaN,Y
461,287471.0,2003 AK46,2003 AK46,EOS,A,S,C,NaN,2.53,T,...,NaN,NaN,0.33,2.0,NaN,NaN,NaN,NaN,NaN,Y
462,288286.0,2004 AT12,2004 AT12,EOS,A,S,C,NaN,2.69,M,...,NaN,NaN,NaN,NaN,HN,NaN,NaN,NaN,NaN,Y
463,324798.0,2007 HO20,2007 HO20,EOS,A,S,C,NaN,2.03,T,...,NaN,NaN,1.31,2.0,-,NaN,NaN,NaN,NaN,Y
464,346759.0,2009 BV46,2009 BV46,EOS,A,S,C,NaN,1.82,T,...,NaN,NaN,0.80,2.0,NaN,NaN,NaN,NaN,NaN,Y
465,353778.0,2012 HA77,2012 HA77,EOS,A,S,C,NaN,2.40,T,...,NaN,NaN,0.64,2.0,+,NaN,NaN,NaN,NaN,Y
466,357911.0,2005 VR131,2005 VR131,EOS,A,S,C,NaN,2.24,M,...,NaN,NaN,0.36,1.0,NaN,NaN,NaN,NaN,NaN,NaN
467,362493.0,2010 TM25,2010 TM25,EOS,A,S,C,NaN,2.17,T,...,NaN,NaN,0.73,2.0,NaN,NaN,NaN,NaN,NaN,Y
468,370227.0,2002 OC27,2002 OC27,EOS,A,S,C,NaN,2.06,T,...,NaN,NaN,0.57,2.0,NaN,NaN,NaN,NaN,NaN,Y
469,385893.0,2006 SJ232,2006 SJ232,EOS,A,S,C,NaN,2.05,T,...,NaN,NaN,0.54,2.0,NaN,NaN,NaN,NaN,NaN,Y
470,397062.0,2005 UX149,2005 UX149,EOS,A,S,C,NaN,1.78,T,...,NaN,NaN,0.54,2.0,NaN,NaN,NaN,NaN,NaN,Y
471,425326.0,2010 AS55,2010 AS55,EOS,A,S,C,NaN,1.56,T,...,NaN,NaN,0.83,3.0,-,NaN,NaN,NaN,NaN,Y
472,428958.0,2008 YM91,2008 YM91,EOS,A,S,C,NaN,2.24,M,...,NaN,NaN,NaN,NaN,HN,NaN,NaN,NaN,NaN,Y
473,NaN,2011 WJ33,2011 WJ33,EOS,A,S,M,NaN,2.82,M,...,>,NaN,0.16,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [46]:
EOS_FAM.sort_values('DIA').head()

,NUMBER,NAME,DESIG,FAM,S,CLASS,S.1,F,DIA,S.2,...,F.3,AMIN,AMAX,U,NOTES,BIN,PRI,SAM,SD,WF
471,425326.0,2010 AS55,2010 AS55,EOS,A,S,C,NaN,1.56,T,...,NaN,NaN,0.83,3.0,-,NaN,NaN,NaN,NaN,Y
470,397062.0,2005 UX149,2005 UX149,EOS,A,S,C,NaN,1.78,T,...,NaN,NaN,0.54,2.0,NaN,NaN,NaN,NaN,NaN,Y
464,346759.0,2009 BV46,2009 BV46,EOS,A,S,C,NaN,1.82,T,...,NaN,NaN,0.80,2.0,NaN,NaN,NaN,NaN,NaN,Y
452,202321.0,2005 EG55,2005 EG55,EOS,A,S,C,NaN,2.01,T,...,NaN,NaN,0.59,2.0,NaN,NaN,NaN,NaN,NaN,Y
463,324798.0,2007 HO20,2007 HO20,EOS,A,S,C,NaN,2.03,T,...,NaN,NaN,1.31,2.0,-,NaN,NaN,NaN,NaN,Y